import DefaultPage from '@/components/DefaultPage'
import Sidebar from '@/components/Sidebar'
import Head from 'next/head'
import styled from 'styled-components'

export default function Home() {
  return (
    <Container>
      <Head>
        <title>Whatsapp</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Sidebar />
      <DefaultPage />
    </Container>
  )
}

const Container = styled.div`
  display: flex;
  padding: 10px;
`
