import DefaultPage from '@/components/DefaultPage'
import Sidebar from '@/components/Sidebar'
import useMediaQuery from '@mui/material/useMediaQuery'
import Head from 'next/head'
import { useRouter } from 'next/router'
import styled from 'styled-components'

export default function Home() {
  const router = useRouter()
  const matches = useMediaQuery('(max-width:780px)')
  if (router.query.fillScreen && matches) {
    return <Sidebar />
  } else {
    return (
      <Container>
        <Head>
          <title>Whatsapp</title>
          <meta name='description' content='Generated by create next app' />
          <meta name='viewport' content='width=device-width, initial-scale=1' />
          <link rel='icon' href='/logo.webp' />
        </Head>
        {!matches && <Sidebar />}
        <DefaultPage />
      </Container>
    )
  }
}

const Container = styled.div`
  display: flex;
`
